# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

name: got-scotch-api
dependencies:
- jupyter
- pandas=0.17.1
- pip
- pip:
    - dill
    - jupyter_kernel_gateway
